site_name: Aiming Documentation
docs_dir: 'src'
site_dir: 'docs'
nav:
  - Home: ./index.md
  - Examples:
    - Index: ./examples/index.md
    - Namecall: ./examples/namecall.md
    - Aim Lock: ./examples/aimlock.md
  - Aiming:
    - Get Closest Target Part To Cursor: ./aiming/getclosesttargetparttocursor.md
    - Get Closest To Cursor: ./aiming/getclosesttocursor.md
    - Selected: ./aiming/selected.md
    - Settings: ./aiming/settings.md
    - Signals: ./aiming/signals.md
    - Update FOV: ./aiming/updatefov.md
  
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences